"""add_playbook_sync_runs_table

Revision ID: 817b6dd86ea2
Revises: f9dda305f950
Create Date: 2026-03-29 17:44:55.541957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '817b6dd86ea2'
down_revision: Union[str, Sequence[str], None] = 'f9dda305f950'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playbook_sync_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('input_source', sa.Text(), nullable=True),
    sa.Column('output_path', sa.Text(), nullable=True),
    sa.Column('trigger_type', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playbook_sync_runs_job_id'), 'playbook_sync_runs', ['job_id'], unique=False)
    op.create_index(op.f('ix_playbook_sync_runs_status'), 'playbook_sync_runs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playbook_sync_runs_status'), table_name='playbook_sync_runs')
    op.drop_index(op.f('ix_playbook_sync_runs_job_id'), table_name='playbook_sync_runs')
    op.drop_table('playbook_sync_runs')
    # ### end Alembic commands ###
