"""baseline_full_schema

Revision ID: f9dda305f950
Revises: 
Create Date: 2026-03-08 16:05:23.674113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f9dda305f950'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('legal_name', sa.String(length=180), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'name', name='uq_classes_school_name')
    )
    op.create_index('ix_classes_school_id', 'classes', ['school_id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('group', sa.String(length=60), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_school_id'), 'students', ['school_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('reset_token_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('guardians',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('whatsapp_phone', sa.String(length=32), nullable=False),
    sa.Column('relationship', sa.String(length=32), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('receive_whatsapp', sa.Boolean(), nullable=False),
    sa.Column('consent_to_contact', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guardians_school_id'), 'guardians', ['school_id'], unique=False)
    op.create_index(op.f('ix_guardians_student_id'), 'guardians', ['student_id'], unique=False)
    op.create_table('student_classes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'class_id', name='uq_student_class')
    )
    op.create_index('ix_student_classes_class_id', 'student_classes', ['class_id'], unique=False)
    op.create_index('ix_student_classes_student_id', 'student_classes', ['student_id'], unique=False)
    op.create_table('student_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('mood', sa.String(length=50), nullable=True),
    sa.Column('participation', sa.String(length=50), nullable=True),
    sa.Column('signals_observed', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_submitted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_reports_created_at'), 'student_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_student_reports_school_id'), 'student_reports', ['school_id'], unique=False)
    op.create_index(op.f('ix_student_reports_student_id'), 'student_reports', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_reports_teacher_id'), 'student_reports', ['teacher_id'], unique=False)
    op.create_table('teacher_classes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'class_id', name='uq_teacher_class')
    )
    op.create_index('ix_teacher_classes_class_id', 'teacher_classes', ['class_id'], unique=False)
    op.create_index('ix_teacher_classes_teacher_id', 'teacher_classes', ['teacher_id'], unique=False)
    op.create_table('ai_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('requested_by_user_id', sa.UUID(), nullable=True),
    sa.Column('contexts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('queued', 'running', 'done', 'failed', name='ai_job_status'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['student_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_jobs_report_id'), 'ai_jobs', ['report_id'], unique=False)
    op.create_index(op.f('ix_ai_jobs_requested_by_user_id'), 'ai_jobs', ['requested_by_user_id'], unique=False)
    op.create_index(op.f('ix_ai_jobs_school_id'), 'ai_jobs', ['school_id'], unique=False)
    op.create_table('ai_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('generated_by_user_id', sa.UUID(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('teacher_version', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parent_version', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signals_detected', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('guardrails_passed', sa.Boolean(), nullable=False),
    sa.Column('guardrails_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['generated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['student_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_reports_created_at'), 'ai_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_reports_report_id'), 'ai_reports', ['report_id'], unique=False)
    op.create_index(op.f('ix_ai_reports_school_id'), 'ai_reports', ['school_id'], unique=False)
    op.create_index(op.f('ix_ai_reports_student_id'), 'ai_reports', ['student_id'], unique=False)
    op.create_table('ai_fallback_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('ai_report_id', sa.UUID(), nullable=True),
    sa.Column('topic_nucleo', sa.String(length=64), nullable=True),
    sa.Column('context', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('model_output_summary', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['ai_report_id'], ['ai_reports.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['student_reports.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fallback_created_at', 'ai_fallback_events', ['created_at'], unique=False)
    op.create_index('idx_fallback_resolved_at', 'ai_fallback_events', ['resolved_at'], unique=False)
    op.create_index('idx_fallback_school_id', 'ai_fallback_events', ['school_id'], unique=False)
    op.create_table('share_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('ai_report_id', sa.UUID(), nullable=False),
    sa.Column('guardian_id', sa.UUID(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ai_report_id'], ['ai_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardians.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('idx_share_links_ai_report_id', 'share_links', ['ai_report_id'], unique=False)
    op.create_index('idx_share_links_expires_at', 'share_links', ['expires_at'], unique=False)
    op.create_index('idx_share_links_school_id', 'share_links', ['school_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_share_links_school_id', table_name='share_links')
    op.drop_index('idx_share_links_expires_at', table_name='share_links')
    op.drop_index('idx_share_links_ai_report_id', table_name='share_links')
    op.drop_table('share_links')
    op.drop_index('idx_fallback_school_id', table_name='ai_fallback_events')
    op.drop_index('idx_fallback_resolved_at', table_name='ai_fallback_events')
    op.drop_index('idx_fallback_created_at', table_name='ai_fallback_events')
    op.drop_table('ai_fallback_events')
    op.drop_index(op.f('ix_ai_reports_student_id'), table_name='ai_reports')
    op.drop_index(op.f('ix_ai_reports_school_id'), table_name='ai_reports')
    op.drop_index(op.f('ix_ai_reports_report_id'), table_name='ai_reports')
    op.drop_index(op.f('ix_ai_reports_created_at'), table_name='ai_reports')
    op.drop_table('ai_reports')
    op.drop_index(op.f('ix_ai_jobs_school_id'), table_name='ai_jobs')
    op.drop_index(op.f('ix_ai_jobs_requested_by_user_id'), table_name='ai_jobs')
    op.drop_index(op.f('ix_ai_jobs_report_id'), table_name='ai_jobs')
    op.drop_table('ai_jobs')
    op.drop_index('ix_teacher_classes_teacher_id', table_name='teacher_classes')
    op.drop_index('ix_teacher_classes_class_id', table_name='teacher_classes')
    op.drop_table('teacher_classes')
    op.drop_index(op.f('ix_student_reports_teacher_id'), table_name='student_reports')
    op.drop_index(op.f('ix_student_reports_student_id'), table_name='student_reports')
    op.drop_index(op.f('ix_student_reports_school_id'), table_name='student_reports')
    op.drop_index(op.f('ix_student_reports_created_at'), table_name='student_reports')
    op.drop_table('student_reports')
    op.drop_index('ix_student_classes_student_id', table_name='student_classes')
    op.drop_index('ix_student_classes_class_id', table_name='student_classes')
    op.drop_table('student_classes')
    op.drop_index(op.f('ix_guardians_student_id'), table_name='guardians')
    op.drop_index(op.f('ix_guardians_school_id'), table_name='guardians')
    op.drop_table('guardians')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_students_school_id'), table_name='students')
    op.drop_table('students')
    op.drop_index('ix_classes_school_id', table_name='classes')
    op.drop_table('classes')
    op.drop_table('schools')
    # ### end Alembic commands ###
